# A composed figure: several figures side by side / stacked, by patchwork.
#
#   plots:   name -> a whole figure design (its own data, stats, plot, layers)
#   compose: layout: "mean | box" -- the plots' names with | / + - ( )
#            add:    calls after the layout, each `op: "+"` (default) or "&"
#                    (plot_layout, plot_annotation, theme ...)
#   plot:    only the saved size (width, height, dpi, units)
#
# Each figure reads its own data (no shared data): its data and figure
# parts are written as for a figure alone, as fig_<name>. A figure that is
# itself a patchwork (panels below it) or a ggsurvfit with add_risktable is
# wrapped with wrap_elements(), so the layout and plot_annotation(tag_levels)
# see it as one figure; add_risktable's table is kept only once the
# ggsurvfit is built (ggsurvfit_build()).

.fig_compose_fields <- c("layout", "add")
.fig_compose_plot_fields <- c("width", "height", "dpi", "units")

# the layout's tokens: names, the operators, brackets; NULL if another
# character is in it
.fig_layout_tokens <- function(layout) {
  x <- gsub("\\s+", "", as.character(layout)[1L])
  tok <- regmatches(x, gregexpr("[A-Za-z][A-Za-z0-9_.]*|[|/+()-]", x))[[1L]]
  if (paste(tok, collapse = "") != x) return(NULL)
  tok
}

.fig_layout_default <- function(design) paste(names(design$plots), collapse = " | ")

.fig_layout_code <- function(layout, nms) {
  tok <- .fig_layout_tokens(layout)
  if (is.null(tok)) stop("compose$layout: only the plots' names and | / + - ( ) may be used", call. = FALSE)
  is_nm <- grepl("^[A-Za-z]", tok)
  miss <- setdiff(tok[is_nm], nms)
  if (length(miss)) stop("compose$layout: no plot named ", paste(miss, collapse = ", "), call. = FALSE)
  tok[is_nm] <- paste0("fig_", tok[is_nm])
  out <- paste(tok, collapse = " ")
  out <- gsub("( ", "(", out, fixed = TRUE)
  gsub(" )", ")", out, fixed = TRUE)
}

# compose$add[[i]]: the call, and "+" or "&"
.fig_compose_add_code <- function(a, gg, name = "fig") {
  op <- a$op %||% "+"
  spec <- a[setdiff(names(a), "op")]
  res <- .fig_call_code(spec, target = name, plus = TRUE, ggplot2_version = gg)
  if (identical(op, "&")) {
    res$line <- sub(sprintf("^%s <- %s \\+ ", name, name),
                    sprintf("%s <- %s & ", name, name), res$line)
  }
  res
}

.fig_compose_code <- function(design, plot_id, gg, setup = FALSE, save = TRUE,
                              name = "fig", levels = NULL) {
  nms <- names(design$plots)
  # each figure is made as fig_<name>; one that is wrapped (a patchwork of
  # panels, a risk table) is made as `fig` first
  bodies <- lapply(seq_along(nms), function(i) {
    d <- .fig_as_design(design$plots[[i]])
    # (the code lists once, at the head: below)
    b <- .fig_design_body(d, gg, setup = setup, levels = levels,
                          codelists_head = FALSE)
    if (b$risktable || b$patch) b else
      .fig_design_body(d, gg, setup = setup, name = paste0("fig_", nms[i]),
                       levels = levels, codelists_head = FALSE)
  })
  comp <- design$compose %||% list()
  layout <- .fig_layout_code(comp$layout %||% .fig_layout_default(design), nms)
  adds <- lapply(comp$add %||% list(), .fig_compose_add_code, gg = gg$version,
                 name = name)
  libs <- unique(c(unlist(lapply(bodies, `[[`, "libs")), "patchwork",
                   unlist(lapply(adds, `[[`, "libs"))))
  needs <- unique(c(unlist(lapply(bodies, `[[`, "needs")), unlist(lapply(adds, `[[`, "pkgs"))))
  guard <- .fig_guard_code(c(unlist(lapply(bodies, `[[`, "guard_v")), unlist(lapply(adds, `[[`, "guard"))),
                           c(unlist(lapply(bodies, `[[`, "features")), unlist(lapply(adds, `[[`, "features"))))
  one <- function(i) {
    nm <- nms[i]
    b <- bodies[[i]]
    keep <- if (b$risktable) {
      c("# one figure: the curves with their number at risk (built), wrapped",
        sprintf("fig_%s <- wrap_elements(full = ggsurvfit_build(fig))", nm))
    } else if (b$patch) {
      c("# one figure with its panels, wrapped",
        sprintf("fig_%s <- wrap_elements(full = fig)", nm))
    }
    c(section(sprintf("figure %d (%s): data", i, nm)),
      b$step1,
      section(sprintf("figure %d (%s): the figure", i, nm)),
      b$step2,
      keep,
      "")
  }
  code <- c(
    sprintf("# %s: composed figure (%s)", plot_id, paste(nms, collapse = ", ")),
    sprintf("# Generated by tflspec %s from the figure's design.",
            utils::packageVersion("tflspec")),
    if (gg$explicit) sprintf("# Written for ggplot2 %s", gg$version),
    "",
    paste0("library(", libs, ")"),
    if (length(needs)) sprintf("# also needs: %s (called as pkg::fn)", paste(needs, collapse = ", ")),
    if (length(guard)) c("", guard),
    "",
    if (length(levels)) .codelists_head(levels),
    unlist(lapply(seq_along(nms), one)),
    section("the figures together"),
    sprintf("%s <- %s", name, layout),
    unlist(lapply(adds, `[[`, "line")),
    if (save) c(name, "", .fig_save_code(design$plot, plot_id, name)))
  structure(.code_lines(code), class = "tfl_code")
}

.fig_as_design <- function(x) {
  if (inherits(x, "tfl_fig_design")) x else .fig_design_from_list(x)
}

.fig_check_compose <- function(design, adam, gg) {
  out <- data.frame(part = character(), field = character(), problem = character(),
                    stringsAsFactors = FALSE)
  add <- function(p, f, x) out[nrow(out) + 1L, ] <<- list(p, f, x)
  nms <- names(design$plots)
  if (is.null(nms) || any(!nzchar(nms)) || any(make.names(nms) != nms) || anyDuplicated(nms)) {
    add("plots", "names", "each plot needs a name of letters, digits, _ and . (starting with a letter), once")
  }
  for (sec in c("data", "stats", "layers")) {
    if (length(design[[sec]])) add(sec, sec, "a composed design has its data, statistics and layers in each of its plots, not at the top")
  }
  for (f in setdiff(names(design$plot), .fig_compose_plot_fields)) {
    add("plot", f, "a composed design's plot holds only the saved size (width, height, dpi, units)")
  }
  for (nm in nms) {
    sub <- .fig_as_design(design$plots[[nm]])
    if (length(sub$plots)) add(paste0("plots$", nm), "plots", "a plot of a composed design cannot itself be composed")
    if (!is.null(sub$ggplot2_version)) add(paste0("plots$", nm), "ggplot2_version", "set ggplot2_version at the top of the design")
    p <- tfl_check_fig_design(sub, adam, gg$version)
    for (r in seq_len(nrow(p))) add(paste0("plots$", nm, " ", p$part[r]), p$field[r], p$problem[r])
  }
  comp <- design$compose %||% list()
  for (f in setdiff(names(comp), .fig_compose_fields)) add("compose", f, "is not a field of compose (layout, add)")
  if (!is.null(comp$layout)) {
    tok <- .fig_layout_tokens(comp$layout)
    if (is.null(tok)) {
      add("compose", "layout", "only the plots' names and | / + - ( ) may be used")
    } else {
      used <- tok[grepl("^[A-Za-z]", tok)]
      for (m in setdiff(used, nms)) add("compose", "layout", paste0("no plot named ", m))
      for (m in setdiff(nms, used)) add("compose", "layout", paste0("plot ", m, " is not in the layout"))
      if (is.null(tryCatch(str2lang(paste(tok, collapse = " ")), error = function(e) NULL))) {
        add("compose", "layout", "does not parse")
      }
    }
  }
  adds <- comp$add %||% list()
  for (i in seq_along(adds)) {
    a <- adds[[i]]
    part <- sprintf("compose.add[%d]", i)
    if (!(a$op %||% "+") %in% c("+", "&")) add(part, "op", "must be + or &")
    spec <- a[setdiff(names(a), "op")]
    extra <- .fig_check_call(spec, part)
    for (r in seq_len(nrow(extra))) add(extra$part[r], extra$field[r], extra$problem[r])
    e <- .fig_compat_walk(spec, gg$version, part)$errors
    for (r in seq_len(nrow(e))) add(e$part[r], e$field[r], e$problem[r])
  }
  out
}

# the advice of each plot, its part prefixed and its fixes aimed at it
.fig_advice_compose <- function(design, adam, ggplot2_version) {
  gg <- .fig_target_version(ggplot2_version, design)
  rows <- lapply(names(design$plots), function(nm) {
    a <- tfl_fig_advice(.fig_as_design(design$plots[[nm]]), adam, gg$version)
    if (!nrow(a)) return(a)
    a$part <- paste0("plots$", nm, " ", a$part)
    a$fix <- I(lapply(a$fix, function(f) if (!is.null(f)) c(f, list(plot = nm))))
    a
  })
  # the compose calls' own (ggplot2 version) advice
  top <- .fig_advice_df(.fig_advice_rules()$gg_compat(design, list(gg = gg)))
  do.call(rbind, c(rows, list(top)))
}
