# The figure style standard: every look-and-feel value of a figure in one
# catalog, so that every figure of a study -- generated by pp_*(), written by
# hand, or written by an AI -- looks the same.
#
# The built-in catalog is taken from the three sample programs the figure
# generators were built from (KM of duration of response, waterfall of the
# best percent change, swimmer of the best overall response).  A company
# writes its own in a workbook (tfl_fig_style_template() / tfl_read_fig_style()) and
# sets it with options(tflspec.fig_style = tfl_read_fig_style(path)); tflplanner
# passes its company standards the same way.
#
#   settings  type, key, value   one value; `type` blank = every figure,
#                                km / waterfall / swimmer = that type only
#   colors    palette, value, colour   named palettes (value = the data value
#                                it colours) and ordered ones (value blank)
#   markers   marker, shape, fill, colour, size   event and symbol markers

.fs_df <- function(...) data.frame(..., stringsAsFactors = FALSE)

.fig_style_builtin <- function() {
  s <- function(type, key, value, note) .fs_df(type = type, key = key,
                                               value = value, note = note)
  settings <- rbind(
    # ---- every figure
    s(NA, "base_size", "10", "base font size (pt) of the theme"),
    s(NA, "axis_title_size", "10", "axis titles (pt)"),
    s(NA, "axis_text_size", "8", "axis tick labels (pt)"),
    s(NA, "legend_text_size", "9", "legend text (pt)"),
    s(NA, "legend_key_size", "0.7", "legend key size (lines)"),
    s(NA, "legend_ncol", "3", "manual legend panel: columns"),
    s(NA, "legend_height", "0.2", "manual legend panel / plot height"),
    s(NA, "text_size", "3", "text drawn in the panel (mm, geom_text size)"),
    s(NA, "theme", "boxed", "boxed | L_axis | minimal | classic"),
    s(NA, "panel_border_width", "0.5", "boxed: panel border (mm)"),
    s(NA, "axis_line_width", "0.2", "L_axis: axis lines (mm)"),
    s(NA, "tick_width", "0.4", "axis ticks (mm)"),
    s(NA, "tick_length", "2", "axis tick length (mm)"),
    s(NA, "line_width", "0.3", "data lines (mm)"),
    s(NA, "zero_line_colour", "black", "reference line at 0"),
    s(NA, "zero_line_width", "0.5", ""),
    s(NA, "ref_line_colour", "grey", "threshold lines (e.g. +20% / -30%)"),
    s(NA, "ref_linetype", "dashed", ""),
    s(NA, "ref_line_width", "0.5", ""),
    s(NA, "month_days", "30.4375", "days in a month, for day -> month axes"),
    s(NA, "width", "7.3", "output size"),
    s(NA, "height", "4.2", ""),
    s(NA, "units", "in", "in | cm | px"),
    s(NA, "dpi", "300", ""),
    # ---- KM
    s("km", "censor_shape", "x", "censor mark"),
    s("km", "censor_size", "3", ""),
    s("km", "censor_stroke", "0.6", ""),
    s("km", "median_linetype", "twodash", "the 50% line"),
    s("km", "median_colour", "grey50", ""),
    s("km", "median_line_width", "0.3", ""),
    s("km", "y_by", "0.2", "survival axis breaks"),
    s("km", "risk_title", "Number of Patients at Risk", "number at risk panel"),
    s("km", "risk_height", "0.167", "number at risk panel / curve height (1:6)"),
    s("km", "width", "8.33", "2500 x 1438 px at 300 dpi"),
    s("km", "height", "4.79", ""),
    # ---- waterfall
    s("waterfall", "bar_width", "0.8", ""),
    s("waterfall", "ref_lines", "20,-30", "threshold lines (%)"),
    s("waterfall", "ref_label_size", "3.7", "labels of the threshold lines (mm)"),
    s("waterfall", "ref_label_hjust", "-0.3", "outside the panel, right"),
    s("waterfall", "right_margin", "50", "room for the labels (pt)"),
    s("waterfall", "y_min", "-100", ""),
    s("waterfall", "y_max", "100", ""),
    s("waterfall", "y_by", "20", ""),
    s("waterfall", "x_label", "Patients", ""),
    # ---- swimmer
    s("swimmer", "theme", "L_axis", ""),
    s("swimmer", "bar_width", "1.2", "subject bars (mm)"),
    s("swimmer", "marker_size", "1.5", "response at each assessment"),
    s("swimmer", "marker_palette", "response_assessment", ""),
    s("swimmer", "event_size", "1.2", "event markers"),
    s("swimmer", "visit_linetype", "dotted", "visit grid"),
    s("swimmer", "visit_colour", "gray", ""),
    s("swimmer", "visit_label", "Month", ""),
    s("swimmer", "bar_legend_prefix", "Best response", "legend label: <prefix> <response>"),
    s("swimmer", "legend_ncol", "3", "legend panel below the plot"),
    s("swimmer", "legend_height", "0.2", "legend panel / plot height (1:5)"),
    s("swimmer", "legend_point_size", "2.2", ""),
    s("swimmer", "legend_label_size", "2.2", "(mm)"),
    s("swimmer", "width", "7.71", ""),
    s("swimmer", "height", "4.17", "")
  )
  pal <- function(palette, value, colour, note = "") {
    .fs_df(palette = palette, value = value, colour = colour, note = note)
  }
  colors <- rbind(
    pal("treatment", NA, c("blue", "#D55E00", "#009E73", "#CC79A7", "#E69F00",
                           "#56B4E9"),
        c("KM sample (single arm)", rep("", 5))),
    pal("response", c("CR", "PR", "SD", "PD", "NE", "NON-CR/NON-PD"),
        c("#008000", "#0000FF", "#FFA500", "#800080", "#A0A0A0", "#20B2AA"),
        c(rep("waterfall sample", 4), "", "")),
    pal("response_assessment", c("CR", "PR", "SD", "PD", "NE"),
        c("#008000", "#0000CD", "#FF8C00", "#9400D3", "gray"),
        "swimmer sample: the response at each assessment"),
    pal("response_light", c("CR", "PR", "SD", "PD", "NE", "NON-CR/NON-PD"),
        c("#99CC99", "#9999FF", "#FFCC99", "#CC99FF", "#D9D9D9", "#99D8D3"),
        c(rep("swimmer sample: best overall response", 4), "", "")),
    pal("okabe_ito", NA, c("#E69F00", "#56B4E9", "#009E73", "#F0E442",
                           "#0072B2", "#D55E00", "#CC79A7", "#000000")),
    pal("grey", NA, c("#000000", "#555555", "#999999", "#CCCCCC"))
  )
  mk <- function(marker, shape, fill, colour, size, note = "") {
    .fs_df(marker = marker, shape = shape, fill = fill, colour = colour,
           size = size, note = note)
  }
  markers <- rbind(
    mk("Death", "25", "black", "transparent", "1.2", "swimmer sample"),
    mk("Subsequent anti-cancer therapy", "21", "#FF00FF", "transparent", "1.2",
       "swimmer sample"),
    mk("Discontinued", "24", "black", "transparent", "1.2", "swimmer sample"),
    mk("assessment", "23", NA, "transparent", "1.5",
       "swimmer sample: response at each assessment (fill = response)"),
    mk("best_response", "15", NA, NA, "2.2", "legend of the best-response bars"),
    mk("censor", "4", NA, NA, "3", "KM sample: x"))
  list(settings = settings, colors = colors, markers = markers)
}

#' The figure style standard
#'
#' Every look-and-feel value of a figure -- font sizes, line widths, tick
#' lengths, reference lines, the censor mark, colour palettes, event
#' markers, the output size -- in one catalog, so every figure of a study
#' looks the same, whoever (or whatever) writes its code.  The [tfl_fig_km()] /
#' [tfl_fig_waterfall()] / [tfl_fig_swimmer()] generators take their defaults from it,
#' and [tfl_fig_setup_code()] writes it into a helper script for figure programs
#' written by hand.
#'
#' The built-in catalog is taken from the sample programs the generators were
#' built from.  A company keeps its own in a workbook: write the built-in one
#' with `tfl_fig_style_template()`, edit it, read it with `tfl_read_fig_style()` and
#' set it with `options(tflspec.fig_style = tfl_read_fig_style(path))`.
#'
#' * `settings` (`type`, `key`, `value`): one value per key; `type` blank
#'   applies to every figure, `km` / `waterfall` / `swimmer` to that type
#'   (and wins over the blank row).
#' * `colors` (`palette`, `value`, `colour`): a palette whose rows name a
#'   data `value` colours that value (`response`: CR, PR ...); one whose
#'   `value` is blank is used in order (`treatment`).
#' * `markers` (`marker`, `shape`, `fill`, `colour`, `size`): event markers
#'   by label (a swimmer event named `Death` takes the `Death` row) and the
#'   figures' own symbols (`censor`, `assessment`).
#'
#' @param path A workbook.
#' @return `tfl_fig_style()` and `tfl_read_fig_style()`: a list of three data frames;
#'   `tfl_fig_style_template()`: `path`, invisibly.
#' @export
tfl_fig_style <- function() {
  s <- getOption("tflspec.fig_style")
  if (is.null(s)) return(.fig_style_builtin())
  b <- .fig_style_builtin()
  for (k in names(b)) if (is.null(s[[k]])) s[[k]] <- b[[k]]
  s
}

#' @rdname tfl_fig_style
#' @export
tfl_fig_style_template <- function(path) {
  writexl::write_xlsx(.fig_style_builtin(), path)
  invisible(path)
}

#' @rdname tfl_fig_style
#' @export
tfl_read_fig_style <- function(path) {
  b <- .fig_style_builtin()
  have <- readxl::excel_sheets(path)
  out <- lapply(names(b), function(sh) {
    if (!sh %in% have) return(b[[sh]])
    d <- as.data.frame(readxl::read_excel(path, sh, col_types = "text",
                                          trim_ws = FALSE),
                       stringsAsFactors = FALSE)
    miss <- setdiff(setdiff(names(b[[sh]]), "note"), names(d))
    if (length(miss)) {
      stop("Figure style sheet `", sh, "` lacks column(s): ",
           paste(miss, collapse = ", "), call. = FALSE)
    }
    if (!"note" %in% names(d)) d$note <- NA_character_
    d <- d[names(b[[sh]])]
    d[rowSums(!is.na(d)) > 0, , drop = FALSE]
  })
  stats::setNames(out, names(b))
}

# One setting for a figure type: its own row, else the blank-type row.
.fs_get <- function(key, type = NA, style = tfl_fig_style()) {
  s <- style$settings
  v <- s$value[s$key %in% key & s$type %in% type]
  if (!length(v) || is.na(v[1])) v <- s$value[s$key %in% key & is.na(s$type)]
  if (length(v)) v[1] else NA_character_
}

# Every setting of a type, as a named list (the type's rows over the blank).
.fs_all <- function(type = NA, style = tfl_fig_style()) {
  s <- style$settings
  keys <- unique(s$key)
  stats::setNames(lapply(keys, function(k) .fs_get(k, type, style)), keys)
}

# The palettes as tfl_fig_palettes() gives them.
.fs_palettes <- function(style = tfl_fig_style()) {
  cl <- style$colors
  cl <- cl[!is.na(cl$palette) & !is.na(cl$colour), , drop = FALSE]
  out <- lapply(split(cl, factor(cl$palette, levels = unique(cl$palette))),
                function(d) {
                  if (all(is.na(d$value))) d$colour
                  else stats::setNames(d$colour, d$value)
                })
  out
}

# A marker row by label (case-insensitive), or NULL.
.fs_marker <- function(label, style = tfl_fig_style()) {
  m <- style$markers
  i <- match(tolower(label), tolower(m$marker))
  if (is.na(i)) NULL else as.list(m[i, ])
}
