#' Generate ggplot2 code from a plot spec
#'
#' @param spec A spec from [tfl_read_fig_spec()] or [tfl_fig_spec()].
#' @param plot_id Plot id(s); `NULL` = all plots.
#' @param adam Optional ADaM data ([tfl_read_adam()]). When given, codelist values
#'   (colours, factor levels, legend items) are resolved from the data and
#'   written literally into the code; variable labels become axis labels.
#' @return A named character vector of R scripts (one per plot).
#' @export
tfl_fig_code <- function(spec, plot_id = NULL, adam = NULL) {
  spec <- pp_normalize_spec(spec)
  if (!is.null(adam)) adam <- tfl_read_adam(adam)
  ids <- plot_id %or% spec$plots$plot_id
  miss <- setdiff(ids, spec$plots$plot_id)
  if (length(miss)) stop("Unknown plot_id: ", paste(miss, collapse = ", "), call. = FALSE)
  out <- vapply(ids, function(pid) pp_plot_code1(spec, pid, adam), character(1))
  names(out) <- ids
  out
}

#' Write generated code to `.R` files
#'
#' @inheritParams tfl_fig_code
#' @param dir Output folder; files are named `<plot_id>.R`.
#' @return File paths, invisibly.
#' @export
tfl_write_fig_code <- function(spec, dir, plot_id = NULL, adam = NULL) {
  code <- tfl_fig_code(spec, plot_id, adam)
  dir.create(dir, showWarnings = FALSE, recursive = TRUE)
  paths <- file.path(dir, paste0(pp_file_name(names(code)), ".R"))
  for (i in seq_along(code)) writeLines(code[[i]], paths[i], useBytes = TRUE)
  invisible(paths)
}

pp_plot_code1 <- function(spec, pid, adam) {
  ctx <- pp_context(spec, pid, adam)
  gen <- switch(ctx$type,
    km = pp_gen_km,
    waterfall = pp_gen_waterfall,
    swimmer = pp_gen_swimmer
  )
  g <- gen(ctx)

  units <- ctx$prow$units %or% pp_opt(ctx, "units") %or% "in"
  std <- identical(units, pp_opt(ctx, "units"))
  width <- as.numeric(ctx$prow$width %or% (if (std) pp_opt(ctx, "width")) %or%
                        if (units == "px") "2250" else "7.5")
  height <- as.numeric(ctx$prow$height %or% (if (std) pp_opt(ctx, "height")) %or%
                         if (units == "px") "1350" else "4.5")
  dpi <- ctx$prow$dpi %or% pp_opt(ctx, "dpi") %or% "300"
  width_in <- switch(units, "in" = width, cm = width / 2.54, px = width / as.numeric(dpi))

  lg <- pp_legend_code(ctx, g$parts, width_in)
  needs_pw <- !is.null(lg$inset) || !is.null(lg$panel) || length(g$panels) > 0
  libs <- c(setdiff(g$libs, "patchwork"), if (needs_pw) "patchwork")

  # ---- assembly ----
  main_h <- 1 - sum(vapply(g$panels, `[[`, numeric(1), "size"))
  names_v <- c("p", vapply(g$panels, `[[`, character(1), "name"))
  heights <- c(main_h, vapply(g$panels, `[[`, numeric(1), "size"))
  assemble <- character()
  if (!is.null(lg$inset)) assemble <- c(assemble, lg$inset)
  stack <- function(nm, h) {
    if (length(nm) == 1) return(nm)
    sprintf("(%s + plot_layout(heights = %s))", paste(nm, collapse = " / "), vec_code(round(h / sum(h), 3)))
  }
  pnl <- lg$panel
  fig <- if (is.null(pnl)) {
    stack(names_v, heights)
  } else if (pnl$pos %in% c("below", "bottom")) {
    stack(c(names_v, "p_legend"), c(heights * (1 - pnl$size), pnl$size))
  } else if (pnl$pos == "top") {
    stack(c("p_legend", names_v), c(pnl$size, heights * (1 - pnl$size)))
  } else {
    inner <- stack(names_v, heights)
    pair <- if (pnl$pos == "right") c(inner, "p_legend") else c("p_legend", inner)
    w <- if (pnl$pos == "right") c(1 - pnl$size, pnl$size) else c(pnl$size, 1 - pnl$size)
    sprintf("(%s + plot_layout(widths = %s))", paste(pair, collapse = " | "), vec_code(w))
  }
  fig <- sub("^\\((.*)\\)$", "\\1", fig)
  assemble <- c(assemble, sprintf("fig <- %s", fig), "fig")

  fig_path <- gsub("{plot_id}", pid, pp_opt(ctx, "fig_path"), fixed = TRUE)
  lines <- c(
    sprintf("# %s: %s", pid, ctx$def$title),
    if (!is.na(ctx$prow$title)) sprintf("# %s", ctx$prow$title),
    sprintf("# Generated by tflspec %s - a skeleton: edit freely.", utils::packageVersion("tflspec")),
    "",
    paste0("library(", libs, ")"),
    if (ctx$type == "km") "library(survival)",
    "",
    section("data"),
    pp_load_lines(ctx),
    "",
    paste(g$data, collapse = "\n\n"),
    "",
    section("the figure"),
    paste(g$plot, collapse = "\n"),
    "",
    "# ---- legend ----",
    plus_code("p", as.list(lg$theme), append = TRUE),
    if (!is.null(lg$pre)) c("", paste(lg$pre, collapse = "\n\n")),
    "",
    "# ---- assemble ----",
    assemble,
    "",
    section("saving the figure"),
    sprintf("fig_path   <- %s", fig_path),
    sprintf("fig_width  <- %s", format(width)),
    sprintf("fig_height <- %s", format(height)),
    sprintf("fig_dpi    <- %s", dpi),
    sprintf("fig_units  <- %s", q(units)),
    "",
    "dir.create(dirname(fig_path), showWarnings = FALSE, recursive = TRUE)",
    paste0("ggsave(\n",
           "  filename = fig_path,\n",
           "  plot     = fig,\n",
           "  width    = fig_width,\n",
           "  height   = fig_height,\n",
           "  dpi      = fig_dpi,\n",
           "  units    = fig_units\n)")
  )
  paste(lines, collapse = "\n")
}

#' Check a plot spec against ADaM data
#'
#' Reports unknown plot types / layers / presets, missing required roles,
#' variables not in the datasets and codelist values not in the data.
#'
#' @inheritParams tfl_fig_code
#' @return A data frame of issues (`plot_id`, `sheet`, `message`), invisibly.
#'   Issues are also printed.
#' @export
tfl_check_fig_spec <- function(spec, adam = NULL) {
  spec <- pp_normalize_spec(spec)
  if (!is.null(adam)) adam <- tfl_read_adam(adam)
  types <- pp_types()
  issues <- list()
  add <- function(pid, sheet, ...) issues[[length(issues) + 1]] <<- data.frame(plot_id = pid, sheet = sheet, message = paste0(...))
  has_var <- function(ds, var) is.null(adam) || (!is.null(adam[[ds]]) && var %in% names(adam[[ds]]))

  for (i in seq_len(nrow(spec$plots))) {
    p <- spec$plots[i, ]
    pid <- p$plot_id
    if (is.na(p$plot_type) || !p$plot_type %in% names(types)) { add(pid, "plots", "unknown plot_type '", p$plot_type, "'"); next }
    def <- types[[p$plot_type]]
    if (is.na(p$dataset)) add(pid, "plots", "dataset is required")
    else if (!is.null(adam) && is.null(adam[[p$dataset]])) add(pid, "plots", "dataset ", p$dataset, " not in ADaM data")
    layers <- split_list(p$layers)
    for (l in setdiff(layers, names(def$layers))) add(pid, "plots", "unknown layer '", l, "' for ", p$plot_type)
    chk <- list(theme = pp_themes, palette = names(tfl_fig_palettes()), legend_type = pp_legend_types, legend_pos = pp_legend_positions)
    for (k in names(chk)) if (!is.na(p[[k]]) && !p[[k]] %in% chk[[k]]) add(pid, "plots", k, " '", p[[k]], "' is not one of: ", paste(chk[[k]], collapse = ", "))

    r <- spec$roles[spec$roles$plot_id %in% pid, , drop = FALSE]
    r$layer[is.na(r$layer)] <- "base"
    r$dataset[is.na(r$dataset)] <- p$dataset
    for (lay in intersect(c("base", layers), names(def$roles))) {
      req <- names(which(def$roles[[lay]]))
      for (role in setdiff(req, r$role[r$layer == lay])) add(pid, "roles", "required role '", role, "' missing (layer ", lay, ")")
    }
    for (j in seq_len(nrow(r))) {
      if (!r$layer[j] %in% c("base", layers)) add(pid, "roles", "role row for layer '", r$layer[j], "' which is not in plots$layers")
      if (!is.na(r$variable[j]) && !has_var(r$dataset[j], r$variable[j])) add(pid, "roles", r$dataset[j], ".", r$variable[j], " not found")
      if (!is.na(r$shape[j]) && !is_num_string(r$shape[j]) && !r$shape[j] %in% names(pp_shape_names)) add(pid, "roles", "unknown shape '", r$shape[j], "'")
    }
    f <- spec$filters[spec$filters$plot_id %in% pid, , drop = FALSE]
    f$dataset[is.na(f$dataset)] <- p$dataset
    for (j in seq_len(nrow(f))) {
      if (!has_var(f$dataset[j], f$variable[j])) { add(pid, "filters", f$dataset[j], ".", f$variable[j], " not found"); next }
      if (!is.null(adam) && !f$value[j] %in% as.character(adam[[f$dataset[j]]][[f$variable[j]]])) {
        add(pid, "filters", "value '", f$value[j], "' not found in ", f$dataset[j], ".", f$variable[j])
      }
    }
    lv <- spec$levels[spec$levels$plot_id %in% pid, , drop = FALSE]
    if (!is.null(adam)) for (j in seq_len(nrow(lv))) {
      found <- any(vapply(adam, function(d) lv$variable[j] %in% names(d) && lv$value[j] %in% as.character(d[[lv$variable[j]]]), logical(1)))
      if (!found) add(pid, "levels", "value '", lv$value[j], "' of ", lv$variable[j], " not found in the data")
    }
    lg <- spec$legend[spec$legend$plot_id %in% pid, , drop = FALSE]
    for (g in setdiff(lg$glyph[!is.na(lg$glyph)], pp_glyphs)) add(pid, "legend", "unknown glyph '", g, "'")
  }
  bad_opt <- setdiff(spec$options$key, names(pp_default_options()))
  for (k in bad_opt) add(NA_character_, "options", "unknown option key '", k, "'")

  out <- if (length(issues)) do.call(rbind, issues) else data.frame(plot_id = character(), sheet = character(), message = character())
  if (nrow(out)) {
    message(nrow(out), " issue(s):\n", paste(sprintf("  [%s] %s: %s", out$plot_id, out$sheet, out$message), collapse = "\n"))
  } else {
    message("No issues found.")
  }
  invisible(out)
}
