# Quick API for treatment-sequence figures (sankey / sunburst).
#
# These are drawn by tflspec's own ggplot2 functions (tfl_plot_sankey(),
# tfl_plot_sunburst()), so -- unlike the other figure types -- the generated
# script calls tflspec.

pp_seq_header <- function(pid, what, title, libs) {
  c(sprintf("# %s: %s", pid, what),
    if (!is.null(title)) sprintf("# %s", title),
    sprintf("# Generated by tflspec %s - a skeleton: edit freely.", utils::packageVersion("tflspec")),
    "",
    paste0("library(", libs, ")"),
    "")
}

pp_seq_save <- function(pid, width, height, dpi, units) {
  fp <- getOption("tflspec.fig_path") %or% pp_default_options()$fig_path
  c(section("saving the figure"),
    sprintf("fig_path   <- %s", gsub("{plot_id}", pid, fp, fixed = TRUE)),
    sprintf("fig_width  <- %s", format(width)),
    sprintf("fig_height <- %s", format(height)),
    sprintf("fig_dpi    <- %s", format(dpi)),
    sprintf("fig_units  <- %s", q(units)),
    "",
    "dir.create(dirname(fig_path), showWarnings = FALSE, recursive = TRUE)",
    paste0("ggsave(\n  filename = fig_path,\n  plot     = fig,\n  width    = fig_width,\n",
           "  height   = fig_height,\n  dpi      = fig_dpi,\n  units    = fig_units,\n  bg       = \"white\"\n)"))
}

# Step1 shared by sankey and sunburst: load, filter, category colours.
pp_seq_data <- function(adam, data, pop, id, stage, category, palette) {
  ds <- pp_ds_name(data)
  expr <- getOption("tflspec.data_expr") %or% "{ds}"
  rhs <- gsub("{ds}", ds, gsub("{DS}", data, expr, fixed = TRUE), fixed = TRUE)
  df <- if (!is.null(adam)) adam[[data]] else NULL
  if (!is.null(adam) && is.null(df)) stop("Dataset ", data, " not in `adam`.", call. = FALSE)
  if (!is.null(df)) {
    miss <- setdiff(c(id, stage, category), names(df))
    if (length(miss)) stop(data, " has no column(s): ", paste(miss, collapse = ", "), call. = FALSE)
  }
  if (!is.null(pop) && !is.null(df) && !pop %in% names(df)) {
    warning(pop, " is not in ", data, "; population filter skipped.", call. = FALSE)
    pop <- NULL
  }
  pals <- tfl_fig_palettes()
  if (!palette %in% names(pals)) stop("Unknown palette: ", palette, call. = FALSE)
  pal <- unname(pals[[palette]])
  pal_code <- if (!is.null(df)) {
    if (!is.null(pop)) df <- df[df[[pop]] %in% "Y", , drop = FALSE]
    d <- pp_seq_prepare(df, id, stage, category, NULL)
    lv <- attr(d, "levels_order")
    sprintf("pal_cat <- %s", vec_code(stats::setNames(pal[(seq_along(lv) - 1) %% length(pal) + 1], lv)))
  } else {
    paste0("cat_levels <- unique(seq_df$", category, "[order(seq_df$", stage, ")])\n",
           "pal_cat <- setNames(", vec_code(pal), "[seq_along(cat_levels)], cat_levels)")
  }
  c(section("data"),
    if (rhs != ds) sprintf("%s <- %s", ds, rhs) else sprintf("# Input data frame: %s (one row per subject and %s)", ds, stage),
    "",
    pipe_code("seq_df", list(ds, if (!is.null(pop)) sprintf('filter(%s == "Y")', pop))),
    "",
    pal_code)
}

#' Sankey diagram code for treatment sequences
#'
#' The script builds nodes and links with [tfl_sankey_data()] and draws them with
#' [tfl_plot_sankey()].
#'
#' @inheritParams tfl_fig_km
#' @param style `grey_links` (links in light grey), `colored_links` (links in
#'   the colour of their source node) or `subgroups` (one panel per value of
#'   `by`, on a shared scale).
#' @param data Dataset with one row per subject and line.
#' @param id,stage,category Subject, line and category (e.g. treatment class)
#'   variables.
#' @param by Subgroup variable for `style = "subgroups"`.
#' @param palette Palette preset for the categories.
#' @param width,height,dpi,units Figure size.
#' @export
tfl_fig_sankey <- function(adam = NULL, style = c("grey_links", "colored_links", "subgroups"),
                      data = "ADLOT", id = "USUBJID", stage = "LINE", category = "TRT",
                      by = NULL, pop = "FASFL", palette = "treatment", title = NULL,
                      width = 9, height = 5, dpi = 300, units = "in",
                      file = NULL, plot_id = "sankey") {
  style <- match.arg(style)
  adam <- pp_prep_adam(adam)
  if (style == "subgroups" && is.null(by)) stop('`style = "subgroups"` needs `by`.', call. = FALSE)
  if (style != "subgroups") by <- NULL
  sk_call <- sprintf("sk <- tfl_sankey_data(seq_df, id = %s, stage = %s, category = %s%s)",
                     q(id), q(stage), q(category), if (!is.null(by)) paste0(", by = ", q(by)) else "")
  common <- paste0(
    "  node_label = \"label\",\n",
    "  node_value = \"n\",\n",
    "  node_treatment = \"category\",\n",
    "  treatment_palette = pal_cat,\n",
    if (style == "colored_links") "  use_link_color_by_source = TRUE,\n" else "",
    "  link_alpha = 0.55,\n",
    "  label_size = 2.5")
  plot <- if (style == "subgroups") {
    c(sk_call,
      "grps <- unique(sk$nodes$grp)",
      paste0("res <- tfl_plot_sankey_batch(\n",
             "  sk$nodes, sk$links,\n",
             "  subgroup_specs = data.frame(\n",
             "    subgroup = grps,\n",
             "    filter   = sprintf('grp == \"%s\"', grps),\n",
             "    title    = ifelse(grps == \"ALL\", \"All subjects\", paste(", q(by), ", \"=\", grps))\n",
             "  ),\n",
             "  scale_strategy = \"shared_max\",\n",
             "  save_png = FALSE,\n", common, "\n)"),
      paste0("fig <- wrap_plots(res$plots, ncol = 2)",
             if (!is.null(title)) paste0(" +\n  plot_annotation(title = ", q(title), ")") else ""))
  } else {
    c(sk_call,
      paste0("p <- tfl_plot_sankey(\n  sk$nodes, sk$links,\n", common, "\n)",
             if (!is.null(title)) paste0(" +\n  labs(title = ", q(title), ")") else ""),
      "fig <- p")
  }
  libs <- c("dplyr", "ggplot2", if (style == "subgroups") "patchwork", "tflspec")
  code <- paste(c(
    pp_seq_header(plot_id, "Sankey diagram of treatment sequences (tflspec::tfl_plot_sankey)", title, libs),
    pp_seq_data(adam, data, pop, id, stage, category, palette),
    "",
    section("the figure"),
    "# nodes: one per line x category (n = subjects); links: subjects moving to the next line",
    plot, "fig",
    "",
    pp_seq_save(plot_id, if (style == "subgroups" && missing(width)) 12 else width,
                if (style == "subgroups" && missing(height)) 8 else height, dpi, units)
  ), collapse = "\n")
  pp_seq_finish(code, file)
}

#' Sunburst code for treatment sequences
#'
#' The script builds paths with [tfl_sunburst_data()] and draws them with
#' [tfl_plot_sunburst()].
#'
#' @inheritParams tfl_fig_sankey
#' @param style `rings` (one ring per line, inner = first line).
#' @param legend `right`, `bottom` or `none`.
#' @export
tfl_fig_sunburst <- function(adam = NULL, style = "rings",
                        data = "ADLOT", id = "USUBJID", stage = "LINE", category = "TRT",
                        pop = "FASFL", palette = "treatment", legend = "right", title = NULL,
                        width = 6.5, height = 5.5, dpi = 300, units = "in",
                        file = NULL, plot_id = "sunburst") {
  style <- match.arg(style)
  adam <- pp_prep_adam(adam)
  if (!legend %in% c("right", "bottom", "none")) stop("`legend` must be right, bottom or none.", call. = FALSE)
  code <- paste(c(
    pp_seq_header(plot_id, "Sunburst of treatment sequences (tflspec::tfl_plot_sunburst)", title,
                  c("dplyr", "ggplot2", "tflspec")),
    pp_seq_data(adam, data, pop, id, stage, category, palette),
    "",
    section("the figure"),
    "# one row per treatment sequence (L1, L2, ...) with its number of subjects",
    sprintf("paths <- tfl_sunburst_data(seq_df, id = %s, stage = %s, category = %s)", q(id), q(stage), q(category)),
    paste0("p <- tfl_plot_sunburst(\n",
           "  paths,\n",
           "  path_value   = \"n\",\n",
           "  levels       = names(pal_cat),\n",
           "  palette      = pal_cat,\n",
           "  label_min_frac = 0.04,  # no labels on arcs under 4% of the circle\n",
           "  center_label = paste0(\"N = \", n_distinct(seq_df$", id, "))\n)"),
    paste0("fig <- p +\n  theme(legend.position = ", q(legend), ", legend.title = element_blank())",
           if (!is.null(title)) paste0(" +\n  labs(title = ", q(title), ")") else ""),
    "fig",
    "",
    pp_seq_save(plot_id, width, height, dpi, units)
  ), collapse = "\n")
  pp_seq_finish(code, file)
}

pp_seq_finish <- function(code, file) {
  if (!is.null(file)) {
    dir.create(dirname(file), showWarnings = FALSE, recursive = TRUE)
    writeLines(code, file, useBytes = TRUE)
  }
  structure(code, class = "tfl_code")
}
